### PR TITLE
DSL: add test for multi-line m paragraph

### PR DESCRIPTION
**Pull request by soshial**

### CODE REVIEW

**Comment by ilius** [comment]
Why are they UTF-16?
They are harder to work with.

If you want to test it can detect encoding, there should be one dedicated test file for it.

**Comment by soshial** [comment]
Because, strictly speaking, UTF-16LE is the only allowed encoding of DSL files (as standard). DSL compiler can't compile files in other encodings.

There are many DSL files in UTF8, but only Goldendict can open them. So UTF16 is not a special case, it's the default case.

**Comment by ilius** [comment]
Please convert these to `.txt` with PR #492 then convert the `.txt` to `.hdir` and open it in browser (with `file:///Users/soshial/.../test.hdir/00000.html`) and confirm the produced html is correct.

**Comment by soshial** [comment]
I am driving today and tomorrow and I will be free to add test files it tomorrow.

**Comment by soshial** [comment]
Could you please try how Goldendict renders this DSL?

```
Адонис
	[m1]      ([p]греч.[/p] Adonis, от [p]финик.[/p] Адон - господин) - [p]греч.[/p] [p]назв.[/p] финикийского божества растительности и плодородия, соответствующего [p]вавилон.[/p] Таммузу. Культ А. известен со 2-го тыс. до н. э., а с нач. 1-го тыс. распространялся по [p]финик.[/p] колониям в Средиземноморье и затем проник в Грецию (в [p]греч.[/p] мифологии А. - возлюбленный Афродиты).[/m]
	\ 
	[m1][p]Лит.:[/p] Baudissin W. W., Adonis und Esmun, Lpz., 19U.
```

The documentation mentions that putting spaces after [m1] should create indent for the first line:

Screenshot 2023-06-26 at 17 57 41

**Comment by soshial** [comment]
I added tests:
* `001-m-tag_one-liner_unclosed-paragraphs.dsl` OK
* `001-empty-lines-br.dsl` OK
* `001-headword-with-formatting.dsl` BUG (formatting should not be part of headword text, but formatting should be shown as part of glossary entry's body)
* `002-m-tag_multiline-paragraph.dsl` **BUG (last line gets indent, but it shouldn't)**

Also,
`\<<typical card\>>` is rendered as `[ref]typical card[/ref]`
should be rendered as `<<typical card>>`

**Comment by ilius** [comment]
Please open a new issue for `001-headword-with-formatting.dsl` and remove it from here, since I don't think it works for master branch either.

**Comment by soshial** [comment]
No empty lines should be between paragraphs.

Screenshot 2023-06-26 at 19 29 07

**Comment by soshial** [comment]
> Please open a new issue for 001-headword-with-formatting.dsl and remove it from here, since I don't think it works for master branch either.

Let's just ignore this test file for now?

**Comment by ilius** [comment]
Yes.

**Comment by soshial** [comment]
I believe that all TXT Tabfiles are correct now.

**Pull request merged**
