### PR TITLE
DSL: add a sample with all additional files

### PR DESCRIPTION
**Pull request by soshial**

### CODE REVIEW

**Comment by ilius** [comment]
Please recode all dsl files to UTF-8.
Except these 2 which I have added to pyglossary's tests:
- `001-empty-lines-br.dsl`
- `002-m-tag_multiline-paragraph.dsl`

and that's enough for purpose of testing encoding detection.
Git does not detect UTF-8, neither do command line tools like `less`, `grep` etc or most editors. It's just a waste of time.

**Comment by ilius** [comment]
Also change your target branch to `dsl` please.

**Comment by soshial** [comment]
OK, I will also add utf8 or utf16le postfix to filenames for clarity, do you mind?

**Comment by ilius** [comment]
No need.
Maybe I rename the 2 utf-16 myself later.

**Comment by soshial** [comment]
Done.

**Pull request merged**
