### PR TITLE
DSL: add dict with unclosed [m] tags

### PR DESCRIPTION
**Pull request by soshial**

### CODE REVIEW

**Comment by ilius** [comment]
It's too large.
Please limit it to 20 entries.
Also the number at the beginning of file name should be the number of entries.

**Comment by ilius** [comment]
Sorry I thought it's many entries.

**Comment by ilius** [comment]
Rename to `001-unclosed-m-tags.dsl`.

**Comment by soshial** [comment]
Rename and added another test.

**Pull request merged**
